# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c894b7517c2e46ce296700dc86142ebf61f2161f2237c466b2b9e60915445b2a38e89d192835e92c6bf3172b395fcfbcbce7f5b6f1678e645f276676fd97450

test:
  secret_key_base: 564691eda70d46ab7dc7779815bef5b9a7ecae53ce85c568567f8c68fe588bcf49de31f825c33909a2e7d963ff5a8f7704892527f7fd864a494e5c9e82f23a2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
